
name: OptaCloud

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Optacloud check
        uses: nachiketshilwant1/Optacloud_Actions@main
        with:
          api_key: ${{ secrets.DEV_API_TOKEN }}
